### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by jameskolwolf1** [jameskolwolf1/World-Bank#1]
- [x] Look at more native-react videos and different libraries that can to used
- [x] Get a nice design going (in the works)
- [x] Do research on what database you want to use
- [x] Think about going into typescript (Remember the type of data) 
- [x] Look for libraries that have to deal with graphic and statical data

**Comment by jameskolwolf1** [comment]
- [ ] Look at algorithms and see when need to be tested
- [x] Start making better designs and pages for the app
- [x]  looking a financial plans/tool 
- [x] Look at the backend, going to javascript/typescript (85%) (Might was to do java (15%) )

**Comment by jameskolwolf1** [comment]
- [ ] Need to work on the back end, remember the project got easred and you back at the middle again
- [ ] To get user input and access the database
- [ ] When that is complete, add more componets like menu and back button and start to add graph and data charts
